package models

import "go.mongodb.org/mongo-driver/bson/primitive"

// struct defining how data will be stored in DB
// ToDoList is uppercase because it is exported
type ToDoList struct {
	ID     primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"` // object ID generated by MongoDB
	Task   string             `json:"task,omitempty"`                     // actual task data
	Status bool               `json:"status,omitempty"`                   // true or false

}
